# ==========================================
# BLESS - CLUSTER CONFIGURATION / PIPELINE
# ==========================================

# ğŸ–¥ï¸ CLUSTER (Slurm)
[slurm]
partition           = "CPUQ"          # Cluster queue
account             = "viviamsb"      # Project (if applies)
time                = "24:00:00"        # Time limit â³

nodes               = 18                # Number of nodes ğŸ§©
ntasks_per_node     = 14                # MPI tasks per node ğŸš€

output              = "bless_%j.out"    # Standard log ğŸ“„
error               = "bless_%j.err"    # Error log â—
auto_submit         = true              # Automatic sbatch launch ğŸ§š

# ğŸ§¬ ENVIRONMENT
[env]
preamble = """
module load intel/2024a
module load SciPy-bundle/2024.05-gfbf-2024a
module load Python/3.12.3-GCCcore-13.3.0
"""

# ğŸ§  BLESS configuration
[bless]
default_sampling = 10                       # When no --sampling ğŸ§®
media_targets = ["EGFR", "IGF1R", "MET"]    # Media nodes ğŸŒ
timeout_sampling = 300                      # Sampling threshold (seconds) â±ï¸
timeout_paths = 600                         # CountPaths threshold (seconds) â±ï¸
